apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper-tts
  namespace: airadio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper-tts
  template:
    metadata:
      labels:
        app: piper-tts
    spec:
      containers:
      - name: piper-tts
        image: rhasspy/wyoming-piper:latest
        args:
          - --voice
          - nl_BE-nathalie-medium
          - --data-dir
          - /home/piper/.local/share/piper
          - --download-dir
          - /home/piper/.local/share/piper
